authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 5h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: config/search.json
#choice: true, false
useAnnotation: false
tuner:
  builtinTunerName: GridSearch
trial:
  command: python run_nni.py
  codeDir: .
  gpuNum: 1